# Generated by Django 4.1.4 on 2022-12-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.ImageField(max_length=11, upload_to='')),
                ('track', models.CharField(choices=[('FRONTEND', 'frontend'), ('BACKEND', 'backend'), ('FULL_STACK', 'full_stack'), ('PRODUCT_DESIGN', 'product_design')], max_length=20)),
            ],
        ),
    ]
