# Generated by Django 4.1.4 on 2022-12-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_csv',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
