# Generated by Django 4.1.4 on 2022-12-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_bio_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Bio',
            new_name='bio',
        ),
    ]
